### ISSUE TITLE
nenes-converter is not working

### ISSUE THREAD

**Issue by zeyuyun1** [sweatersjpg/NENES#1]
Hi, I try to use the nenes converter you made at https://sweaters.itch.io/nenes-converter

However, the result I receive from inputing a png sprite file cannot be loaded by nenes. The output I received from the converter:

var spriteSheet = "|Jn?2.2?|Y?2,?2|S?5.?.,2/?/|P?=5][.[,<?2|P?%*=][=[2<_[/2?5|K?[%=]=2_*[{?,2<,/,?|J?[*=[=[<?2!?<[_,_./|J?_=6_+*=[3+_,?|F?5_=8_=_2+=,?|E?2,=*_[=7*2_<2,3?|E?*2[2_3=2_7[3<3?|D?,=_*=_3=5_2=[=,?5|C?[3_2=_3=_2=_[=3,?2|E?2,_[=_2=_3=_2[2=[=[?3|D?[_4=_6=_2=2[2,2?2|C?2,_8=_2=5_[=[,?|u?9,2=_8=7_2[=,?2|r?3.,<3.[,[=3_2*2_5=4[=<=<_[?2|p?2,<[=b_2*2_7=6<=2[?|p.,=_2*3_=6_7[_5[_=[=<_[=,?|o?<=_7=6_3=[<2[_5[4=<_,_?|o?.[_7=6_6=<3_6[=<_[=,|o?.<=_9=2_8=2<,_3*_2[2<_,_?|n?2.[=_j=2[,_2*3_=<2[.,?|n?<,=2_i=3[,_2*3_[,<.2?|n?<2,=2_8=_4=_3=4<,_2*3=<.3?|o?2=<[=_8=_2=3_2=3[2,<_3*2[,.2?|p?,=<2=2_*2_4=3[2_<[2?3,2<_3*_.?.2?|o?<[2?.[=_*4_=2,3=2?5|?.2_3=,?,2?|p?=_?3[=_2*3_[,3.2,|8.?[_<.,2?2|p?_=?|?.[_2*2_[,[2<.2?|9?[_2?,<?|p?,_[?|2?.[_*_2[3,.2?|a?<_2?<2?|j?3|2?2_3?|3.[=2_2[=,2?|c?}(^}>)?|k?.?2,2=_?|2?2<[=2*=[?<2?|d?)()>(>?|j?.[=_=_?2|?<_<_2*,?,<,?|e?})(?(2?|k?2<[_?2|2?@2&^.?2,.?.|f?2(2?2(2?|k?4|4?>@&}?>2}2?5|d?(3?(2?|u?>)2?2>()>)3?|c?)(2}?()?|u?2}(3)?)(4?|b?)&^2&?(2?|u?}&@>@?2}&>&?|c?^(^(?(2?|v?c|c?9|e"

I believe this result is a little strange because it seems what you get for your Depressed game is an array of number from 0-9. Is there anything I did wrong?

**Comment by sweatersjpg** [comment]
Hi! I didn't think anyone would use NENES!
I think this version is pretty out of date, I've changed the way the converter works, it compresses it into a string like that and NENES should convert that string back into an array of numbers from 0 to however many colours you had
